name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👈 allows manual triggering

permissions:
  contents: write  # 👈 required for push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to public directory
      run: |
        mkdir public
        cp -r src/* public/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
